<a href="https://colab.research.google.com/github/ravibishnoiii/Deep-Learning-with-PyTorch/blob/main/Deep_Learning_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning with PyTorch

## Matrices:
rectangular array of numbers



*   Tensors (PyTorch)
*   Ndarrays (NumPy)




Creating matrices

In [1]:
arr = [[1,2],[3,4]]
arr

[[1, 2], [3, 4]]

In [3]:
import numpy as np


In [4]:
#converting to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [2]:
import torch

In [7]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

Create Matrices with Default Values

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [16]:
np.random.rand(2,2)

array([[0.87320335, 0.03205594],
       [0.5142556 , 0.04409385]])

In [19]:
torch.rand(2,2)


tensor([[0.4066, 0.1120],
        [0.3875, 0.1723]])

### **Seeds for Reproducibility** :
We need seeds to enable reproduction of experimental results. This becomes critical later on where we can easily let people reproduce our code's output exactly as we've produced.

In [23]:
# Creating seed to enable fixed numbers for random number generation
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [24]:
#Repeating random array generation to check
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [26]:
# creating a pytorch tensor with a fixed seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [27]:
# repeating to check
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

NumPy to torch


In [31]:
np_array = np.ones((2,2))
print(np_array)
print(type(np_array))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


In [32]:
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
print(type(torch_tensor))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


We can Create PyTorch tensor from a different numpy datatypes:

Supported types are -

*   double
*   float
*   int64, int32, uint8




In [34]:
# for example
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [35]:
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

Torch to NumPy

In [37]:
torch_tensor = torch.ones(2,2)
type(torch_tensor)

torch.Tensor

In [38]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

**Tensor Operations**

Resizing tensor

In [39]:
a = torch.ones(2,2)
a.size()

torch.Size([2, 2])

In [41]:
a.view(4)

tensor([1., 1., 1., 1.])

In [42]:
a.view(4).size()

torch.Size([4])

Element-wise Addition

In [4]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [5]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [6]:
c = a+b
c

tensor([[2., 2.],
        [2., 2.]])

In [7]:
c=torch.add(a,b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [8]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [9]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [12]:
print(a.sub(b))
print(a)

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[0., 0.],
        [0., 0.]])


In [13]:
print(a.sub_(b))
print(a)

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [15]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [16]:
a*b

tensor([[0., 0.],
        [0., 0.]])

In [17]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [18]:
# Not in-place
print(torch.mul(a, b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [19]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [20]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [21]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [22]:
torch.div(b, a)

tensor([[0., 0.],
        [0., 0.]])

In [23]:
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

**Tensor Mean**

In [24]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [25]:
a.mean(dim=0)

tensor(5.5000)

In [26]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.size()

torch.Size([2, 10])

In [28]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

**Tensor Standard Deviation**

In [29]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)